trigger:
- main

pool:
  name: newsA
  vmImage: ubuntu-latest
steps:
- script: sudo apt-get update
- script: sudo apt-get install docker.io  -y
- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: 'nippy'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'


