trigger:
- main

pool:
  name: newsA
  vmImage: ubuntu-latest
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: 'nippy'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

