trigger:
- main

pool:
  name: newsA
  vmImage: ubuntu-latest
steps:
- script: sudo apt-get install docker -y
- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: 'nippy'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- script: sudo apt-get install docker -y

